version: "4"

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 80:80
        volumes:
            - ./src:/var/www/html/

    mysql_db:
        image: mysql:latest
        command: --default-authentication-plugin=caching_sha2_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - mysql-data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin:latest
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1

volumes:
    mysql-data:
