# ignored options for 'xampp'
# --detach
version: "3.3"
services:
    xampp:
        container_name: feedbackApp
        hostname: 906685fc0057
        volumes:
            - "/Users/a.curran/my_web_pages:/www"
        ports:
            - "41061:22"
            - "41062:80"
        restart: no
        runtime: runc
        platform: linux/amd64
        image: tomsik68/xampp
        command: "sh /startup.s"
